# Tested on Mac OS X 10.9 using clang compiler provided by XCode
package:
    name: opencv
    version: 2.4.11

source:
    fn: opencv-2.4.11.zip
    url: https://github.com/Itseez/opencv/archive/2.4.11.zip

build:
    number: 0

requirements:
    build:
        - cmake
        - numpy
        - jpeg
        - zlib
        - libpng
        - python
    run:
        - python
        - numpy
        - jpeg
        - zlib
        - libpng
test:
    imports:
      - cv2
      - cv2.cv

about:
    home: http://opencv.org/
    license: BSD
